// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdegOdn3CVFA3NBQAVfOZwRQ4X1E_bHyo',
    appId: '1:543714986610:web:089d3282283b0e130390eb',
    messagingSenderId: '543714986610',
    projectId: 'anime-app-aa3ae',
    authDomain: 'anime-app-aa3ae.firebaseapp.com',
    storageBucket: 'anime-app-aa3ae.appspot.com',
    measurementId: 'G-D9ET0SW7WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5LXTaRV4z44xSPkUduoHuIVDHEhg7Bhs',
    appId: '1:543714986610:android:a0c104cf521fb8f90390eb',
    messagingSenderId: '543714986610',
    projectId: 'anime-app-aa3ae',
    storageBucket: 'anime-app-aa3ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDglrwmON1qFyhMUUzAfkSxTwigREcYSxk',
    appId: '1:543714986610:ios:414dc116341dda340390eb',
    messagingSenderId: '543714986610',
    projectId: 'anime-app-aa3ae',
    storageBucket: 'anime-app-aa3ae.appspot.com',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDglrwmON1qFyhMUUzAfkSxTwigREcYSxk',
    appId: '1:543714986610:ios:414dc116341dda340390eb',
    messagingSenderId: '543714986610',
    projectId: 'anime-app-aa3ae',
    storageBucket: 'anime-app-aa3ae.appspot.com',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdegOdn3CVFA3NBQAVfOZwRQ4X1E_bHyo',
    appId: '1:543714986610:web:3d4dad3b3f542bd80390eb',
    messagingSenderId: '543714986610',
    projectId: 'anime-app-aa3ae',
    authDomain: 'anime-app-aa3ae.firebaseapp.com',
    storageBucket: 'anime-app-aa3ae.appspot.com',
    measurementId: 'G-8K0B5WWRP9',
  );
}
